import { TimeBasedId } from "./time-based-id";

export interface UuidV1IdProps {
  id: string;
  timestamp: Date;
  node: string;
  isRandomNode: boolean;
  clockSequence: number;
}

export const UuidV1Id = ({ id, timestamp, node, isRandomNode, clockSequence }: UuidV1IdProps) => (
  <TimeBasedId
    id={id}
    timestamp={timestamp}
    formatName="v1 UUID"
    formatHref="https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)"
  >
    <table style={{ width: "100%" }}>
      <tbody style={{ textAlign: "left" }}>
        <tr>
          <th scope="row">Node (MAC address)</th>
          <td>
            <code>{node}</code>{" "}
            {isRandomNode ? "(randomly generated, not a real MAC)" : "(likely a real MAC address)"}
          </td>
        </tr>
        <tr>
          <th scope="row">Clock sequence</th>
          <td>{clockSequence}</td>
        </tr>
      </tbody>
    </table>
    {isRandomNode ? (
      <p>
        The node field has its multicast bit set, which indicates the generator used a random value
        rather than a network card&rsquo;s MAC address. The same random node is usually reused for
        the lifetime of the process, so it can still be used to link IDs generated by the same
        machine.
      </p>
    ) : (
      <p>
        The node field looks like a real MAC address. That identifies the network card of the
        machine that generated the ID, which can reveal hardware vendor and be used to link every ID
        that machine has ever generated.
      </p>
    )}
  </TimeBasedId>
);
